
t = {
    'en': {
        'welcome': "Welcome! Please enter your Instagram username.",
        'inactive_account': "Your account is inactive. Please contact support.",
        'username_not_found': "Telegram username not found. Please try again.",
        'username_prompt': "Great! Now, please enter your Instagram password.",
        'login_failed': "Login failed. Please try again. Enter your username.",
        'login_error': "Login error: {error}. Please try again. Enter your username.",
        'choose_action': "Choose an action:",
        'upload_type_prompt': "Choose how to upload {upload_type}:",
        'media_received': "Media received. Please provide a caption for your post.",
        'unsupported_media': "Unsupported media type from the URL.",
        'download_failed': "Failed to download from Instagram URL: {error}",
        'successful_upload': "{upload_type} successful!",
        'user_info': "User Info for {username}:\nFull Name: {full_name}\nFollowers: {followers}\nFollowing: {following}",
        'get_hashtag_info_prompt': "Please provide the hashtag to get info.",
        'get_user_info_prompt': "Please provide the username to get info.",
        'logout_success': "Logged out. Enter your username to login again.",
        'action_buttons': {
            'upload_image_story': "Upload Image Story",
            'upload_video_story': "Upload Video Story",
            'upload_photo': "Upload Photo",
            'upload_video': "Upload Video",
            'upload_album': "Upload Album",
            'upload_igtv': "Upload IGTV",
            'upload_clip': "Upload Clip",
            'get_user_info': "Get User Info",
            'get_hashtag_info': "Get Hashtag Info",
            'download_instagram': "Download from Instagram",
            'logout': "Logout",
        }
    },
    'ar': {
        'welcome': "مرحبًا! يرجى إدخال اسم مستخدم إنستغرام الخاص بك.",
        'inactive_account': "حسابك غير نشط. يرجى الاتصال بالدعم.",
        'username_not_found': "لم يتم العثور على اسم مستخدم تلجرام. يرجى المحاولة مرة أخرى.",
        'username_prompt': "رائع! الآن، يرجى إدخال كلمة مرور إنستغرام الخاصة بك.",
        'login_failed': "فشل تسجيل الدخول. يرجى المحاولة مرة أخرى. أدخل اسم المستخدم الخاص بك.",
        'login_error': "خطأ في تسجيل الدخول: {error}. يرجى المحاولة مرة أخرى. أدخل اسم المستخدم الخاص بك.",
        'choose_action': "اختر إجراءً:",
        'upload_type_prompt': "اختر كيف تريد تحميل {upload_type}:",
        'media_received': "تم استلام الوسائط. يرجى تقديم تعليق لمنشورك.",
        'unsupported_media': "نوع الوسائط غير مدعوم من الرابط.",
        'download_failed': "فشل في التنزيل من رابط إنستغرام: {error}",
        'successful_upload': "تم {upload_type} بنجاح!",
        'user_info': "معلومات المستخدم لـ {username}:\nالاسم الكامل: {full_name}\nعدد المتابعين: {followers}\nعدد المتابعين: {following}",
        'get_hashtag_info_prompt': "يرجى تقديم الهاشتاج للحصول على المعلومات.",
        'get_user_info_prompt': "يرجى تقديم اسم المستخدم للحصول على المعلومات.",
        'logout_success': "تم تسجيل الخروج. أدخل اسم المستخدم الخاص بك لتسجيل الدخول مرة أخرى.",
        'action_buttons': {
            'upload_image_story': "رفع صورة للقصة",
            'upload_video_story': "رفع فيديو للقصة",
            'upload_photo': "رفع صورة",
            'upload_video': "رفع فيديو",
            'upload_album': "رفع ألبوم",
            'upload_igtv': "رفع فيديو IGTV",
            'upload_clip': "رفع مقطع",
            'get_user_info': "الحصول على معلومات المستخدم",
            'get_hashtag_info': "الحصول على معلومات الهاشتاج",
            'download_instagram': "تنزيل من إنستغرام",
            'logout': "تسجيل الخروج",
        }
    }
}